import type { Movement, Product } from "@/lib/types"

// Available product categories. In a real app these would likely come
// from their own table / endpoint.
export const CATEGORIES = [
  "Electrónica",
  "Periféricos",
  "Accesorios",
  "Oficina",
  "Redes",
] as const

// Seed products used to render the prototype. Replace this with a
// Supabase query (e.g. supabase.from("products").select()) later.
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Laptop Pro 14\"",
    sku: "LP-14-001",
    description: "Portátil de 14 pulgadas con 16GB de RAM y 512GB SSD.",
    category: "Electrónica",
    price: 1499.99,
    stock: 24,
    imageUrl: "",
    status: "in_stock",
  },
  {
    id: "2",
    name: "Teclado Mecánico RGB",
    sku: "TM-RGB-204",
    description: "Teclado mecánico retroiluminado con switches rojos.",
    category: "Periféricos",
    price: 89.9,
    stock: 7,
    imageUrl: "",
    status: "low_stock",
  },
  {
    id: "3",
    name: "Mouse Inalámbrico Ergo",
    sku: "MS-ERG-118",
    description: "Mouse ergonómico inalámbrico de 6 botones.",
    category: "Periféricos",
    price: 34.5,
    stock: 0,
    imageUrl: "",
    status: "out_of_stock",
  },
  {
    id: "4",
    name: "Monitor 27\" 4K",
    sku: "MN-27-4K",
    description: "Monitor UHD de 27 pulgadas con panel IPS.",
    category: "Electrónica",
    price: 379.0,
    stock: 15,
    imageUrl: "",
    status: "in_stock",
  },
  {
    id: "5",
    name: "Hub USB-C 7 en 1",
    sku: "HB-USBC-7",
    description: "Adaptador multipuerto con HDMI, USB 3.0 y lector SD.",
    category: "Accesorios",
    price: 49.99,
    stock: 5,
    imageUrl: "",
    status: "low_stock",
  },
  {
    id: "6",
    name: "Silla Ergonómica Mesh",
    sku: "SL-ERG-330",
    description: "Silla de oficina con soporte lumbar y reposabrazos 3D.",
    category: "Oficina",
    price: 219.0,
    stock: 42,
    imageUrl: "",
    status: "in_stock",
  },
  {
    id: "7",
    name: "Router WiFi 6",
    sku: "RT-WIFI6-88",
    description: "Router de doble banda con velocidad AX3000.",
    category: "Redes",
    price: 129.99,
    stock: 9,
    imageUrl: "",
    status: "low_stock",
  },
  {
    id: "8",
    name: "Webcam Full HD",
    sku: "WC-FHD-512",
    description: "Cámara web 1080p con micrófono integrado.",
    category: "Periféricos",
    price: 59.0,
    stock: 33,
    imageUrl: "",
    status: "in_stock",
  },
]

// Seed stock movements (audit log). Replace with a Supabase query later.
export const MOCK_MOVEMENTS: Movement[] = [
  {
    id: "m1",
    date: "2026-06-24T09:12:00.000Z",
    productId: "1",
    productName: "Laptop Pro 14\"",
    type: "entrada",
    quantity: 10,
    reason: "Reposición de proveedor",
  },
  {
    id: "m2",
    date: "2026-06-24T11:45:00.000Z",
    productId: "3",
    productName: "Mouse Inalámbrico Ergo",
    type: "salida",
    quantity: 12,
    reason: "Venta mayorista",
  },
  {
    id: "m3",
    date: "2026-06-23T16:30:00.000Z",
    productId: "2",
    productName: "Teclado Mecánico RGB",
    type: "salida",
    quantity: 5,
    reason: "Venta en tienda",
  },
  {
    id: "m4",
    date: "2026-06-23T08:05:00.000Z",
    productId: "5",
    productName: "Hub USB-C 7 en 1",
    type: "entrada",
    quantity: 20,
    reason: "Compra inicial",
  },
  {
    id: "m5",
    date: "2026-06-22T14:20:00.000Z",
    productId: "7",
    productName: "Router WiFi 6",
    type: "salida",
    quantity: 3,
    reason: "Devolución a proveedor",
  },
  {
    id: "m6",
    date: "2026-06-21T10:00:00.000Z",
    productId: "4",
    productName: "Monitor 27\" 4K",
    type: "entrada",
    quantity: 15,
    reason: "Reposición de proveedor",
  },
]
